function AppAbout() {
  
  return (
    <div style={{maxWidth: '700px', margin: 'auto'}}>
      <h1>Development of A Coal Washability Analysis Application Thesis Progress Report</h1>
      <p>Written by <i>Jye Doepel</i></p>
      <div style={{height: '1px', width: '100%', backgroundColor: '#213547'}}></div>
      <p style={{ margin: '1px', textIndent: '2em', textAlign: 'justify', marginTop:'1.5em' }}>This thesis is being undertaken under the supervision of Associate Professor Ernest Baafi, specializing in minerals industry IT related problems, Raymond Tolhurst on coal preparation technical matters, and Kevin Marston, who has expertise in both IT and mineral processing.</p>
      <h2>Abstract</h2>
      <p style={{ margin: '1px', textIndent: '2em', textAlign: 'justify' }}>This thesis progress reports presents the progress made towards the development of an automated coal washability analysis application designed to simplify the complex and error-prone manual process of constructing coal washability curves. Coal washability analysis is critical for optimizing coal preparation processes, helping operators determine the most efficient separation densities to maximize product quality and yield. However, traditional methods rely on labour-intensive calculations that can lead to inefficiencies and inaccuracies.</p>
      <p style={{ margin: '1px', textIndent: '2em', textAlign: 'justify', marginTop:'1.5em' }}>The proposed application automates these calculations by leveraging modern web technologies, including React.js for the front-end interface and FastAPI for the back-end processing. The application uses the Python libraries NumPy and SciPy to handle complex mathematical computations, enabling the automated generation of washability curves from user-provided data such as ash content and specific gravity.</p>
      <p style={{ margin: '1px', textIndent: '2em', textAlign: 'justify', marginTop:'1.5em' }}>By offering real-time interactive visualizations of washability curves, the tool supports quick and informed decision-making for coal preparation plant operators and serves as an educational resource for students learning about coal beneficiation. This project fills a gap in the current literature by providing an accessible and cost-effective solution to washability analysis, demonstrating the potential for digital transformation in the coal industry.</p>



      <h2>1. Introduction</h2>
      <h3>1.1 Dense Medium Separation</h3>
      <p style={{ margin: '1px', textIndent: '2em', textAlign: 'justify' }}>Coal is a key component in many critical industries, facilitating the operation of much of our essential infrastructure (Minerals Council of Australia, 2024). For this coal to be effective in any critical application, the raw coal extracted from mines must undergo a cleaning process to remove impurities such as ash, sulphur, and moisture (Groppo, 2017). Through the removal of these impurities, the coals energy efficiency, environmental impact, and marketability are all ideally optimized (Groppo, 2017). This process of coal cleaning is known as coal beneficiation or coal washing and one of the most common techniques for this process is the dense medium separation (Groppo, 2017).</p>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>DMS utilises the differences in density between the lighter coal and shale (ash), separating out several different fractions (or products) of the raw mined coal, each with a different composition of ash (Meyer & Craig, 2014). The principle of DMS is a simple one, a bath with a density between the desired and undesired material is developed and the raw coal is added. The lighter material (lower ash content) will float, and the heavier material (higher ash content) will sink (Groppo, 2017). In general, it is also necessary for the products of the DMS process to undergo further washing in order to remove and recycle the suspension solids that are undesired for the final product (Groppo, 2017).</p>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>The accuracy of the separation in the DMS process is crucial for coal preparation plants in order to optimize both economic value of their products and marketability, as well as desired performance in operation (Burton, et al., 1991). Figure 1.2 shows a rough relationship between AUD value of the coal product and the ash content of the product coal. In reality, the exact value of a given coal product is very dynamic and a function of a number of variables (Lin, 2023), not just its ash content, however, this can be used as a rough guide. Figure 1.2 illustrates that a reduction in ash content of coal exponentially increase the price of the coal product.</p>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>For a coal preparation plant to decide on its optimized separation density, an analysis of the raw coal input must be undertaken. The analysis typically used for dense medium separation plants is a coal washability analysis (SAHU, 2013). This analysis involves the performance of sink-float tests on a representative sample of the raw coal input across a range of densities. The floats and sinks of each test are analysed to determine their ash percentage. This data can be used to produce a number of washability curves that together can allow coal preparation plant operators to make educated decisions around optimal separation densities (Tolhurst, 2024).</p>
      <h3>1.2 The Coal Washability Curves</h3>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>As ash is more dense than clean coal, the ash content of a fraction of coal increases as the density of the fraction increases (Kentucky Geological Survey, 2024). This feature can be exploited through the use of sink float trials (Kentucky Geological Survey, 2024). Small scale tests are carried out using large beakers to determine the coal ash content at different specific gravities, typically ranging from 1.3 - 1.9 SG (Tolhurst, 2024). </p>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>Starting at the light or heavy end of the beakers typically depends on where the majority of the material will be removed the earliest (Tolhurst, 2024). As samples need to be dried between, removing as much material as early as possible will reduce the time required for drying. If the lightest end is choses, the coal sample will be first placed in the beaker with the lowest specific gravity. The floats of this trial are scooped off the surface, dried, and analysed for ash content. The sinks are then strained, allowed to dry, and then added to the next beaker of increasing specific gravity. Again, the floats in the beaker are scooped off, dried and analysed and the sinks are poured through a strainer, dried, and placed into the next beaker. This is continued for the remainder of the beakers (Tolhurst, 2024).</p>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>From the results obtained from the ash content of each fraction, four washability curves can be developed (Kentucky Geological Survey, 2024):</p>
      <ol>
        <li>The Specific Gravity Curve (Densimetric Curve)</li>
        <li>The Cumulative Floats Curve</li>
        <li>The Cumulative Sinks Curve</li>
        <li>The Instantaneous Ash Curve</li>
      </ol>
      <h4>1.2.1 The Specific Gravity Curve (Densimetric Curve)</h4>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>The specific gravity curve (Figure 1.3) shows the relationship between the density of the separation and the yield of clean coal (floats) (Kentucky Geological Survey, 2024). Thus, if the density of separation is known, then the yield of clean coal can also be found from the graph. By convention, the specific gravity axis is typically on the top horizontal axis and the cumulative weight percentage of floats (yield of clean coal) is typically on the left vertical axis.</p>
      <h4>1.2.2 The Specific Gravity Curve (Densimetric Curve)</h4>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>The cumulative floats curve gives the relationship between the yield of clean coal (floats) and the ash content of the coal (Tolhurst, 2024). Thus, if the required ash content is known, then the yield or cumulative weight percentage of floats can be found from the graph. Conversely, if the yield of clean coal is known, then the expected ash content can be found from the graph. By convention, the ash content axis is typically on the bottom horizontal axis and the cumulative weight percentage of floats (yield of clean coal) is typically on the left vertical axis.</p>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>The cumulative floats curve can be used with the densimetric (specific gravity) curve. If the ash content of the clean coal yield is known, then from the cumulative floats curve, the yield can be obtained. This value for the yield can then be used to find the density of the separation required from the densimetric curve (Tolhurst, 2024).</p>
      <h4>1.2.3 The Cumulative Sinks Curve</h4>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>The cumulative sink curve gives the relationship between the yield of sinks and the ash content of the sinks. So, if the yield of the sinks is known, then the ash content of the sinks can be found from the graph. Conversely, if the ash of the sinks is known then the yield of sinks can be found from the graph (Tolhurst, 2024).</p>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>The cumulative sink curve can be used with the cumulative float curve and the densimetric curve. If the ash of the floats is known, then the yield of the floats can be obtained from the cumulative floats curve. If the density is known, then the yield of floats can be obtained from the densimetric curve. In either case the yield of sinks is known, so the ash of the sinks can be found from the cumulative sinks curve (Tolhurst, 2024).</p>
      <h4>1.2.4 The Instantaneous Ash Curve</h4>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>The Instantaneous ash curve (characteristic ash curve) gives the relationship between the yield of the floats and the ash content of the particle that just floats or just sinks at that yield. It thus gives the highest ash in the floats or the lowest ash in the sinks (Tolhurst, 2024).</p>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>The instantaneous ash curve can be used with the other three washability curves, the specific gravity curve, the cumulative float curve, and the cumulative sink curve (Tolhurst, 2024).</p>
      <h3>1.3 Problem Statement</h3>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>Accurate interpretation of these washability curves is essential for coal preparations operators to determine the optimal separation densities for their desired coal products. Issues can however arise when through manual interpretation of the raw coal washability analysis data as interpretation involves manually complex mathematical calculations, which can be time-consuming and prone to error. It is here that the use of automated computer application for the analysis of this coal washability data is crucial in optimising both the quality and economic value of the final products.</p>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>The complexity of manual calculations poses several challenges:</p>
      <ol>
        <li><b>Time and Labor:</b> Processing large datasets of coal properties is a slow and tedious process that takes up valuable time for plant operators and engineers.</li>
        <li><b>Error Potential:</b> The manual nature of these calculations increases the likelihood of mistakes, leading to inaccurate washability curves.</li>
        <li><b>Educational Barriers:</b> For students or newcomers to coal preparation processes, understanding how to conduct and interpret washability analysis can be overwhelming without automated tools.</li>
        <li><b>Decision-Making Delays:</b> The time-consuming nature of manual calculations can delay key decision-making processes in coal preparation plants, potentially leading to inefficiencies and lower product yields</li>
      </ol>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>Given these challenges, there is a clear need for a modern, digital tool that can automate coal washability analysis, making it more accessible and efficient for both students and industry professionals. This project addresses that need by developing a computer-based computational model for generating coal washability curves, which eliminates the need for manual calculations.</p>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>The main goal of this project is to develop an easy-to-use application that automates coal washability calculations and provides interactive visual representations of coal washability curves. The application will serve as a resource for both students learning about coal beneficiation processes and plant operators who need to quickly and accurately determine the best strategies for coal separation.</p>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>At its core, the project seeks to address the following objectives:</p>
      <ol>
        <li><b>Automation of Washability Analysis:</b> The application will automate the process of generating coal washability curves based on user-provided data, such as ash content and weight percentages at various specific gravities.</li>
        <li><b>Interactive Visualization:</b> The tool will provide an intuitive, interactive interface that allows users to input data and view the resulting coal washability curves in real-time. This will enable users to understand how different separation strategies impact coal quality and yield.</li>
        <li><b>Reduction of Manual Calculations:</b> By automating the washability analysis, the tool will eliminate the need for manual mathematical calculations, saving users time and reducing the risk of errors.</li>
        <li><b>Enhanced Educational Resource:</b> For students, the application will serve as a practical learning tool, helping them understand coal preparation processes and the significance of washability analysis in industrial applications.</li>
        <li><b>Support for Decision-Making:</b> For plant operators, the application will provide a fast and reliable way to determine optimal separation strategies, aiding in decision-making and improving plant efficiency.</li>
      </ol>
      <h3>1.4 Technical Approach</h3>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>The proposed application will blend modern web-based technologies and data processing tools to ensure both a user-friendly product and a product that can handle the complex calculations. On the user facing (front end) side, the popular JavaScript framework React.js will be employed. React.js simplifies building dynamic user interface by using a component-based architecture (Gackenheimer, 2015). This decision will assist in management of the user input forms, washability plot visualizations, and streamlined communication with the backend system. Users will have the ability to upload a set of raw sink-float data in a range of formats and enter in the ash percentages of the coal products they desire. The integration of the JavaScript library Plotly will allow for the visualization of the washability curves in a dynamic and interactive format (Li & Bilal, 2021). This integration allows users to delve into the graphs and adjust their inputs to observe how different values impact the results.</p>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>For the backend system, the modern python-based web framework FastAPI is to be used as it is ideal for building high-performance APIs. The backend system’s primary role is to receive requests from the frontend React.js system (the raw sink-float data), provide some data processing, and return the data to be plotted. The combination of FastAPI as a backend system combined with React.js for a frontend system is quickly becoming a popular technology stack for building quick and easy web applications that are also robust and have a modern feel (Gailer, et al., 2024). </p>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>For the complex mathematical calculations and interpretations of the raw sink-float washability data, the python libraries Numpy and SciPy will be utilized. NumPy excels at efficiently handling numerical data and large arrays, while SciPy offers tools for tasks such as curve fitting and optimization (Ranjani, et al., 2019).</p>
      <h3>1.5 Use Case Scenarios</h3>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>To illustrate the practical application of the tool, the following scenario should be considered: A customer requires a Coking Coal with 9.0% ash. The coal plant operator needs to determine the yield of clean coal and the specific gravity at which the separation should occur. Using the application, the operator can input the relevant ash percentages and raw sink-float data obtained by laboratory tests, and the tool will instantly generate a coal washability curve showing the yield of clean coal and the required density of separation.</p>
      <p style={{ margin: '1px', textIndent: '2em', marginTop:'1.5em', textAlign: 'justify' }}>If a secondary Steaming Coal product with a 25.0% average ash can be sold, the operator can use the application to add in the second coal product and calculate the specific gravity for this separation and estimate the percentage of feed that will be recovered as Steaming Coal. The application will also provide the remaining ash percentage in the tailings, allowing the operator to evaluate the efficiency of the entire coal preparation process.</p>




    </div>
  )
}

export default AppAbout;